name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Crear directorio si no existe
          mkdir -p /var/www/notion2

          # Limpiar directorio existente
          rm -rf /var/www/notion2/*

          # Clonar repositorio
          cd /var/www/notion2
          git clone https://github.com/k4ditano/documentaryt.git .

          # Instalar dependencias del frontend y construir
          npm install
          npm run build

          # Instalar dependencias del backend
          cd backend
          npm install

          # Crear archivo .env
          echo "PORT=3001" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRE=24h" >> .env
          echo "NODE_ENV=production" >> .env

          # Asegurar permisos
          chmod 755 /var/www/notion2
          chmod 644 .env

          # Reiniciar aplicación con PM2
          cd ..
          pm2 delete notion2 || true
          pm2 start backend/src/server.js --name notion2 