name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        env:
          CI: false
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
        
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Instalar Node.js si no está presente
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Instalar PM2 globalmente si no está presente
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            
            # Limpiar y preparar el directorio
            sudo rm -rf /var/www/notion2
            sudo mkdir -p /var/www/notion2
            sudo chown -R $USER:$USER /var/www/notion2
            
            # Clonar el repositorio
            cd /var/www
            git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/k4ditano/documentaryt.git notion2
            cd notion2
            
            # Instalar dependencias y construir
            npm install
            npm run build
            
            # Asegurarse de que los directorios necesarios existen
            mkdir -p uploads database
            
            # Detener la aplicación existente si está corriendo
            pm2 delete notion2 || true
            
            # Iniciar la aplicación con PM2
            pm2 start ecosystem.config.cjs 