name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Asegurarse de que estamos en el directorio correcto
          cd /var/www

          # Crear directorio para la base de datos si no existe
          mkdir -p /var/www/notion2_data

          # Eliminar el directorio anterior si existe
          rm -rf notion2
          
          # Crear nuevo directorio
          mkdir notion2
          cd notion2

          # Clonar repositorio
          git clone https://github.com/k4ditano/documentaryt.git .

          # Verificar que estamos en el directorio correcto
          pwd
          ls -la

          # Instalar dependencias del frontend y construir
          echo "Instalando dependencias del frontend..."
          npm install
          echo "Construyendo frontend..."
          npm run build

          # Instalar dependencias del backend
          echo "Instalando dependencias del backend..."
          cd backend
          rm -f package-lock.json
          npm cache clean --force
          npm install

          # Crear archivo .env en el directorio backend
          echo "Configurando variables de entorno..."
          echo "PORT=3001" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRE=24h" >> .env
          echo "NODE_ENV=production" >> .env
          echo "DB_PATH=/var/www/notion2_data/database.sqlite" >> .env

          # Asegurar permisos
          cd ..
          chmod -R 755 /var/www/notion2
          chmod -R 755 /var/www/notion2_data
          chmod 644 backend/.env

          # Reiniciar aplicación con PM2
          echo "Reiniciando aplicación..."
          pm2 delete notion2 || true
          cd backend
          pm2 start src/server.js --name notion2

          # Mostrar estado de PM2
          echo "Estado de PM2:"
          pm2 list
          
          # Mostrar logs iniciales
          echo "Logs de la aplicación:"
          pm2 logs notion2 --lines 20 || true 